name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  chewie: ^1.11.3
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  equatable: ^2.0.7
  ffmpeg_kit_flutter_new: ^1.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  lecle_yoyo_player: ^0.0.8
  path_provider: ^2.1.5
  pip: ^0.0.3
  video_player: ^2.9.5

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
